{
 "title": "1. DEX Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# *Digital Experience Dashboard* #"
   }
  },
  {
   "title": "Analyzer - Performance Overall Score",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(performanceScore) (analyzeraudits)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Analyzer - Accessibility Overall Score",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(accessibilityScore) (analyzeraudits)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Analyzer - Best Practice Overall Score",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(bestpracticesScore) (analyzeraudits)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Analyzer - SEO Overall Score",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(seoscore) (analyzeraudits)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Analyzer - Data Visualization",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "analyzeraudits{applicationName!=\"\", accessibilityScore!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "options": {
    "content": "## Focus on quality with DEX\nAudit your website and obtain opportunities and recommendations to enhance your website's accessibility, performance, and ranking.\n\nWith build-to-build and page-wise comparison, make faster data-driven decisions."
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 17 },
   "options": {
    "content": "###                                                                         Know more about your data "
   }
  },
  {
   "title": "Application",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "analyzeraudits", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pages",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "analyzeraudits", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Scan Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "analyzeraudits", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Analyzer - General Audit Bar",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "avg(analyzeraudits{accessibilityScore!=\"\"}) by (applicationName)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(analyzeraudits{accessibilityScore!=\"\"}) by (applicationName)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(analyzeraudits{bestpracticesScore!=\"\"}) by (applicationName)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(analyzeraudits{seoscore!=\"\"}) by (applicationName)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}