{
 "title": "2. DEX - Performance Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "Custom", "label": "Analyzer - Compare Control" }
  ]
 },
 "panels": [
  {
   "title": "Analyzer - Performance Overall Score",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(performanceScore) (analyzeraudits)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Analyzer - Page Performance",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(performanceScore, pageName) (analyzeraudits)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Analyzer - Metrics",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "avg by(title, numericValue) (analyzerperfmetrics{title=~\"Speed Index|First Contentful Paint|First Meaningful Paint|Largest Contentful Paint|Total Blocking Time|Cumulative Layout Shift\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 9 },
   "options": {
    "content": "# Manual Performance Testing #\n### Below are the areas where you need to test performance manually: ###\n\n- *How much memory is needed to process the request*\n- *Measured by kilobytes per second, throughput shows the amount of bandwidth used during the test*\n- *How much time the CPU needs to process requests*\n- *A measurement of the total numbers of successful or unsuccessful requests*\n- *This the most common measure of load — how many active users at any point*\n- *How many requests are handled*\n- *Calculate percentage of requests resulting in errors compared to all requests*\n- *Measure the longest amount of time it takes to fulfill a request. A peak response time that is significantly longer than average may indicate an anomaly that will create problems*\n- *The average amount of time it takes to deliver every request is a major indicator of quality from a user’s perspective*\n- *How long it takes to receive the first byte after a request is sent*\n- *Total time to send a request and get a response*"
   }
  },
  {
   "title": "Analyzer - Metrics Web Core Vitals",
   "type": "table",
   "gridPos": { "h": 15, "w": 15, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "clockms" } },
   "targets": [
    {
     "expr": "avg by (title,numericValue,description) (analyzerperfmetrics{title=~\"Speed Index|First Contentful Paint|First Meaningful Paint|Largest Contentful Paint|Total Blocking Time|Cumulative Layout Shift\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Analyzer - Performance Server Latency",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg by(pageName, maxServerLatency, numRequests, numTasks, throughput, totalTaskTime) (analyzerperfdiagnostics)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Analyzer - Mime Pie Chart",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by(mimeType) (analyzerperfmetrics)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 34 }, "options": { "content": ">[*Performance Groups*]()" } },
  {
   "title": "Performance Metric Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(analyzerperfmetrics{title=~\"First Contentful Paint|First Meaningful Paint|Speed Index|Time to Interactive|Total Blocking Time|Largest Contentful Paint|Max Potential First Input Delay\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Performance Opportunity Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (title) (analyzerperfoppo))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Performance Network Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (title) (analyzerperfmetrics{title=~\"Network Requests|Network Round Trip Times|Server Backend Latencies|Keep request counts low and transfer sizes small|Avoid enormous network payloads\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Performance Diagnostic Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (title) (analyzerperfmetrics{group=\"Diagnostics\", title!~\"Keep request counts low and transfer sizes small|Avoid enormous network payloads\"}))\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}