{
 "title": "8. DEX - Performance Network Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Control", "label": "Analyzer - Compare Control" }
  ]
 },
 "panels": [
  {
   "title": "Performance Network Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (title) (analyzerperfmetrics{title=~\"Network Requests|Network Round Trip Times|Server Backend Latencies|Keep request counts low and transfer sizes small|Avoid enormous network payloads\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 0 },
   "options": {
    "content": "<span style=\"font-size:40px;\">Performance Group: Network</span>\r\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "options": {
    "content": "# Performance: Network Audits #\n\n*Displays Network Audit with their total count and potential savings in KiB or ms. This indicates, how resource sizes and transfer sizes affects the performance of your website and how it can be reduced.*\n\n*Network Audits are:*\n- *Network Requests*\n- *Network Round Trip Times*\n- *Avoid enormous network payloads*\n- *Keep request counts low and transfer sizes small*\n- *Server Backend Latencies*"
   }
  },
  {
   "title": "Analyzer - Network",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "avg by(title, displayValue) (analyzerperfmetrics{title=~\" Keep request counts low and transfer sizes small|Network Requests|Network Round Trip Times|Server Backend Latencies|Avoid enormous network payloads\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Analyzer - Server Backend Latencies",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "count by(origin, serverResponseTime) (analyzerperfmetrics{title=\"Server Backend Latencies\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": {
    "content": "### Network: Server Backend Latencies audit ###\n*Server latencies can impact web performance. If the server latency of an origin is high, it's an indication the server is overloaded or has poor backend performance*"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": {
    "content": "### Network: Network Round Trip Times audit ###\n*Network round trip times (RTT) have a large impact on performance. If the RTT to an origin is high, it's an indication that servers closer to the user could improve performance. So:*\n- *Faster sites lead to better user engagement*\n- *Faster sites lead to better user retention*\n- *Faster sites lead to higher conversions*"
   }
  },
  {
   "title": "Analyzer - Network Round Trip Times",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "count by(origin, rtt) (analyzerperfmetrics)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Analyzer - Keep request counts low and transfer sizes small",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "count by(resourceType, requestCount, transferSize) (analyzerperfmetrics)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": {
    "content": "### Network: Keep request counts low and transfer sizes small audit ###\n*Reports how many network requests were made and how much data was transferred while your page loaded. This audit pays significant role in calculating budget as:*\n\n- *The Requests and Transfer Size values for the Total row are computed by adding the values for the Image, Script, Font, Stylesheet, Other, Document, and Media rows.*\n\n- *The Third-party column does not factor into the Total row's values. Its purpose is to make you aware of how many of the total requests and how much of the total transfer size came from third-party domains. The third-party requests could be a combination of any of the other resource types.*"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "options": {
    "content": "### Network: Avoid enormous network payloads audit ###\n*Large network payloads are highly correlated with long load times. They also cost users money; for example, users may have to pay for more cellular data. So, reducing the total size of your page's network requests is good for your users' experience on your site. Report shows the total size in kibibytes (KiB) of all resources requested by your page. The largest requests are presented first*"
   }
  },
  {
   "title": "Analyzer - Enormous network payloads",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "count by(url, transferSize) (analyzerperfmetrics{title=\"Avoid enormous network payloads\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 50 },
   "options": {
    "content": "### Network: Network Requests audit ###\n*DevTools supports blocking network requests to see the impact of individual resources being removed or not being available. This can be helpful for understanding the cost individual scripts. (e.g such as third-party embeds or trackers) have on metrics like Total Blocking Time (TBT) and Time to Interactive. Network request report lists the network requests that were made during page load, i.e., the targeted url where this audit is failed, shows the transfer size in KiloBytes with request' start time and its end time and provides resource size with its status code, mime type and its resource type.*\n"
   }
  },
  {
   "title": "Analyzer - Enormous network payloads",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "count by(url, protocol, statusCode, mimeType, resourceType, startTime, endTime, transferSize, resourceSize) (analyzerperfmetrics)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}